### ISSUE TITLE
Customise Icon Background

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [WrathChaos/react-native-colorful-card#1]
Is it possible to change the background of the icon color?
I have tried it, but I somehow cannot change it from white to anything else

**Comment by kuraydev** [comment]
It is not possible, I can make it work today :)

**Comment by mariomurrent-softwaresolutions** [comment]
Okay, don't stress yourself. When you have time its okay

**Comment by kuraydev** [comment]
Here you go :) 
## [Version 0.1.5  🥰](https://github.com/WrathChaos/react-native-colorful-card/releases/tag/0.1.5)

**Comment by mariomurrent-softwaresolutions** [comment]
Awesome thank you
